#if !defined _DB_VERSION_H 
#define _DB_VERSION_H

//The file was automatically generated by the PrePass Application Ver 2.2.83.223, Thu Jan 15 13:18:51 2026

#define DB_VERSION_UNIQ_ID "0xdf7bd922"

#endif //_DB_VERSION_H
